name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master
      
      - 
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/composerize
          tags: |
            type=raw,value=latest

      -
        name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '12'

      -
        name: Build Web
        run: |
            git clone https://github.com/composerize/composerize.git git
            mkdir composerize-website
            cp -r git/packages/composerize-website/. composerize-website
            cd composerize-website
            npm install yarn@1.19.1 -g --force
            yarn add composerize
            make build
            cd build/
            ls -al
            cd ../..
            mkdir -p rootfs/app/web
            cp -r composerize-website/build/* rootfs/app/web
            ls -al rootfs/app/web

      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v3

      - 
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v3
        
      - 
        name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: |
            linux/amd64
            linux/arm/v6
            linux/arm/v7
            linux/arm64/v8
            linux/ppc64le
            linux/s390x
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - 
        name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/composerize
          short-description: A better Composerize Docker image
          readme-filepath: ./README.md