name: Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master
      
      -
        name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '12'

      -
        name: Build Web
        run: |
            git clone https://github.com/composerize/composerize.git git
            mkdir composerize-website
            cd composerize-website
            cp -r git/packages/composerize-website/. composerize-website
            npm install yarn@1.19.1 -g --force
            yarn add composerize
            make build
            cd build/
            ls -al